repos:
  - hooks:
      - args:
          - --style=file
          - -i
        files: ^(.*[.]cpp|.*[.]h)$
        id: clang-format
    repo: https://github.com/ssciwr/clang-format-hook
    rev: v14.0.0
  - hooks:
      - files: ^(.*[.]cpp|.*[.]h)$
        id: cpplint
    repo: https://github.com/cpplint/cpplint
    rev: 1.6.0
  - hooks:
      - args:
          - --inline-suppr
          - --enable=all
          - --suppress=missingIncludeSystem
          - --suppress=missingInclude
          - --suppress=unusedFunction
          - --suppress=unmatchedSuppression
          - --suppress=unusedStructMember
          - --language=c++
          - --std=c++20
          - --error-exitcode=1
        files: ^(.*[.]cpp|.*[.]h)$
        id: cppcheck
    repo: https://github.com/pocc/pre-commit-hooks
    rev: 9a9bbc00895bbdb7670231c2565d4f1309c42905
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.9.1
    hooks:
      - id: commitizen
        stages: [commit-msg]
      - id: commitizen-branch
        stages: [pre-push]
